[tool.poetry]
name = "dataset-extractor-lotus"
version = "0.1.0"
description = ""
authors = ["pamrein <pascal.amrein@unifr.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
